export { default as SEO } from "./seo"
export { default as Home } from "./home"
export { default as Navbar } from "./navbar"
export { default as Footer } from "./footer"
export { default as Hair } from "./hair"
export { default as Skin } from "./skin"
export { default as Policies } from "./policies"
